package com.baling.models.user;

public enum ERightType {
    RIGHT_DELETE,
    RIGHT_ADD,
    RIGHT_UPDATE_STATUS,
    RIGHT_UPDATE_BUYER,
    RIGHT_UPDATE_SELLER,
    RIGHT_UPDATE_LOGISTICS,
    RIGHT_QUERY,
    RIGHT_QUERY_HISTORY
}
